CREATE TABLE ENDERECO(
ID					UNIQUEIDENTIFIER	PRIMARY KEY,
LAGRADOURO			VARCHAR(100)		NOT NULL,
NUMERO				VARCHAR(10)			NOT NULL,
BAIRRO				VARCHAR(50)			NOT NULL,
LOCALIDADE			VARCHAR(100)		NOT NULL,
UF					CHAR(2)				NOT NULL,
CEP					CHAR(8)				NOT NULL,
);
GO

CREATE TABLE FUNCIONARIO(
ID					UNIQUEIDENTIFIER	PRIMARY KEY,
NOME				VARCHAR(150)		NOT NULL,
DATAADIMSSAO		DATE				NOT NULL,
CPF					CHAR(11)			NOT NULL,
MATRICULA			VARCHAR(20)			NOT NULL,
SALARIO				DECIMAL(15,2)		NOT NULL,
CARGO				INT					NOT NULL,
ENDERECO_ID			UNIQUEIDENTIFIER	NOT NULL,
FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO(ID),
CHECK (CARGO BETWEEN 1 AND 6)
);
GO

--Script para criar uma procedure de cadastro de funcionário e endereço
CREATE PROCEDURE SP_INSERIR_FUNCIONARIO
	@NOME				VARCHAR(150),
	@DATAADIMSSAO		DATE,
	@CPF				CHAR(11),
	@MATRICULA			VARCHAR(20),
	@SALARIO			DECIMAL(15,2),
	@CARGO				INT,
	@LAGRADOURO			VARCHAR(100),
	@NUMERO				VARCHAR(10),
	@BAIRRO				VARCHAR(50),
	@LOCALIDADE			VARCHAR(100),
	@UF					CHAR(2),
	@CEP				CHAR(8)

AS
BEGIN
	BEGIN TRANSACTION --Abeindo uma transação

	--Gerando um novo ID para o funcionário
	DECLARE @IDFUNCIONARIO UNIQUEIDENTIFIER = NEWID() 

	--Gerando um novo ID para o endereço
	DECLARE @IDENDERECO UNIQUEIDENTIFIER = NEWID() 

	--Grava o endereço
	INSERT INTO ENDERECO(ID, LAGRADOURO, NUMERO, BAIRRO, LOCALIDADE, UF, CEP)
	values(@IDENDERECO, @LAGRADOURO, @NUMERO, @BAIRRO, @LOCALIDADE, @UF, @CEP)

	--Grava o funcionário
	INSERT INTO FUNCIONARIO(ID, NOME, DATAADIMSSAO, CPF, MATRICULA, SALARIO, CARGO, ENDERECO_ID)
	values(@IDFUNCIONARIO, @NOME, @DATAADIMSSAO, @CPF, @MATRICULA, @SALARIO, @CARGO, @IDENDERECO)

	COMMIT --Finalizando a transação
END
GO